name: Build Sysmon config with all modules
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  generate-config:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Import Merge-SysmonXml.ps1 and generate config
        run: | 
          Import-Module .\Merge-SysmonXml.ps1
          Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml
        shell: pwsh

      - name: Commit and push the changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sysmonconfig.xml
          git diff --cached --quiet || git commit -m "chore: auto-update sysmonconfig.xml"
          git push
