name: Build Attack Matrix
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2
        
      - name: Run matrix update code
        run: |
          tmpfile=$(mktemp)
          tmpout=$(mktemp)
          grep -Po "(technique_id=T\d+(?:\.\d+)?)" sysmonconfig.xml | sort | uniq -c | sed -E 's/^\s*([0-9]+)\s+technique_id=(\S+)/{"score": \1, "technique_id": "\2"}/' | jq -s 'map({techniqueID: .technique_id, score: .score})' > "$tmpfile"
          jq --argjson techniques "$(cat "$tmpfile")" '.techniques = $techniques' ./attack_matrix/Sysmon-modular.json > "$tmpout"
          mv "$tmpout" ./attack_matrix/Sysmon-modular.json
          rm "$tmpfile"
      
      - name: Commit and push the changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./attack_matrix/Sysmon-modular.json
          git diff --cached --quiet || git commit -m "chore: auto-update Sysmon-modular.json"
          git push
